In [58]:
import pandas as pd
import numpy as np
print(pd.__version__)

3.0.1

In [59]:
# reading playstore_apps.csv file
apps_df = pd.read_csv("../data/raw/playstore_apps.csv")
apps_df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,19M,10000.0,Free,0.0,Everyone,Art & Design,07-01-2018,1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,14M,500000.0,Free,0.0,Everyone,Art & Design;Pretend Play,15-01-2018,2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510.0,8.7M,5000000.0,Free,0.0,Everyone,Art & Design,01-08-2018,1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,25M,50000000.0,Free,0.0,Teen,Art & Design,08-06-2018,Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,2.8M,100000.0,Free,0.0,Everyone,Art & Design;Creativity,20-06-2018,1.1,4.4 and up

In [60]:
apps_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10841 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10840 non-null  float64
 4   Size            10841 non-null  str
 5   Installs        10840 non-null  float64
 6   Type            10840 non-null  str
 7   Price           10840 non-null  float64
 8   Content Rating  10840 non-null  str
 9   Genres          10841 non-null  str
 10  Last Updated    10840 non-null  str
 11  Current Ver     10833 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(4), str(9)
memory usage: 1.1 MB

In [61]:
apps_df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='str')

In [62]:
apps_df.shape

(10841, 13)

In [63]:
apps_df.duplicated().sum()

np.int64(483)

In [64]:
#droping duplicate values present
apps_df = apps_df.drop_duplicates(keep='first')

In [65]:
apps_df.duplicated().sum()

np.int64(0)

In [66]:
apps_df.info()

<class 'pandas.DataFrame'>
Index: 10358 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10358 non-null  str
 1   Category        10358 non-null  str
 2   Rating          8893 non-null   float64
 3   Reviews         10357 non-null  float64
 4   Size            10358 non-null  str
 5   Installs        10357 non-null  float64
 6   Type            10357 non-null  str
 7   Price           10357 non-null  float64
 8   Content Rating  10357 non-null  str
 9   Genres          10358 non-null  str
 10  Last Updated    10357 non-null  str
 11  Current Ver     10350 non-null  str
 12  Android Ver     10355 non-null  str
dtypes: float64(4), str(9)
memory usage: 1.1 MB

In [67]:
apps_df['Category'].unique()

<StringArray>
[     'ART_AND_DESIGN',   'AUTO_AND_VEHICLES',              'BEAUTY',
 'BOOKS_AND_REFERENCE',            'BUSINESS',              'COMICS',
       'COMMUNICATION',              'DATING',           'EDUCATION',
       'ENTERTAINMENT',              'EVENTS',             'FINANCE',
      'FOOD_AND_DRINK',  'HEALTH_AND_FITNESS',      'HOUSE_AND_HOME',
  'LIBRARIES_AND_DEMO',           'LIFESTYLE',                'GAME',
              'FAMILY',             'MEDICAL',              'SOCIAL',
            'SHOPPING',         'PHOTOGRAPHY',              'SPORTS',
    'TRAVEL_AND_LOCAL',               'TOOLS',     'PERSONALIZATION',
        'PRODUCTIVITY',           'PARENTING',             'WEATHER',
       'VIDEO_PLAYERS',  'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION',
                 '1.9']
Length: 34, dtype: str

In [68]:
apps_df[apps_df['Category']=='1.9']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,NaN,"1,000+",NaN,0,NaN,NaN,"February 11, 2018",NaN,4.0 and up,NaN

In [69]:
apps_df = apps_df[apps_df['Category'] != '1.9']

In [70]:
apps_df['Category'].unique()

<StringArray>
[     'ART_AND_DESIGN',   'AUTO_AND_VEHICLES',              'BEAUTY',
 'BOOKS_AND_REFERENCE',            'BUSINESS',              'COMICS',
       'COMMUNICATION',              'DATING',           'EDUCATION',
       'ENTERTAINMENT',              'EVENTS',             'FINANCE',
      'FOOD_AND_DRINK',  'HEALTH_AND_FITNESS',      'HOUSE_AND_HOME',
  'LIBRARIES_AND_DEMO',           'LIFESTYLE',                'GAME',
              'FAMILY',             'MEDICAL',              'SOCIAL',
            'SHOPPING',         'PHOTOGRAPHY',              'SPORTS',
    'TRAVEL_AND_LOCAL',               'TOOLS',     'PERSONALIZATION',
        'PRODUCTIVITY',           'PARENTING',             'WEATHER',
       'VIDEO_PLAYERS',  'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION']
Length: 33, dtype: str

In [73]:
apps_duplicates = apps_df.duplicated().sum()

In [74]:
apps_duplicates

np.int64(0)

In [75]:
apps_df['Rating'].unique()

array([4.1, 3.9, 4.7, 4.5, 4.3, 4.4, 3.8, 4.2, 4.6, 3.2, 4. , nan, 4.8,
       4.9, 3.6, 3.7, 3.3, 3.4, 3.5, 3.1, 5. , 2.6, 3. , 1.9, 2.5, 2.8,
       2.7, 1. , 2.9, 2.3, 2.2, 1.7, 2. , 1.8, 2.4, 1.6, 2.1, 1.4, 1.5,
       1.2])

In [84]:
apps_df['Rating'] = apps_df['Rating'].replace(np.nan, 0)

In [85]:
apps_df['Rating'].unique()

array([4.1, 3.9, 4.7, 4.5, 4.3, 4.4, 3.8, 4.2, 4.6, 3.2, 4. , 0. , 4.8,
       4.9, 3.6, 3.7, 3.3, 3.4, 3.5, 3.1, 5. , 2.6, 3. , 1.9, 2.5, 2.8,
       2.7, 1. , 2.9, 2.3, 2.2, 1.7, 2. , 1.8, 2.4, 1.6, 2.1, 1.4, 1.5,
       1.2])

In [86]:
apps_df['Type'].unique()

<StringArray>
['Free', 'Paid', nan]
Length: 3, dtype: str

In [87]:
apps_df[apps_df['Type'] == 'nan']

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver]
Index: []

In [88]:
apps_df['Size'].unique()

<StringArray>
[  '19M',   '14M',  '8.7M',   '25M',  '2.8M',  '5.6M',   '29M',   '33M',
  '3.1M',   '28M',
 ...
  '467k',  '157k',   '44k',  '676k',   '67k',  '552k',  '885k', '1020k',
  '582k',  '619k']
Length: 461, dtype: str

In [89]:
apps_df['Installs'].unique()

array([1.e+04, 5.e+05, 5.e+06, 5.e+07, 1.e+05, 5.e+04, 1.e+06, 1.e+07,
       5.e+03, 1.e+08, 1.e+09, 1.e+03, 5.e+08, 5.e+01, 1.e+02, 5.e+02,
       1.e+01, 1.e+00, 5.e+00, 0.e+00])

In [91]:
apps_df['Installs'] = apps_df['Installs'].replace(np.nan, 0)

In [92]:
apps_df['Installs'].value_counts()

Installs
1.000000e+06    1488
1.000000e+07    1132
1.000000e+05    1129
1.000000e+04    1033
1.000000e+03     890
1.000000e+02     710
5.000000e+06     683
5.000000e+05     517
5.000000e+04     474
5.000000e+03     469
1.000000e+01     385
1.000000e+08     369
5.000000e+02     328
5.000000e+07     272
5.000000e+01     204
5.000000e+00      82
1.000000e+00      67
5.000000e+08      61
1.000000e+09      49
0.000000e+00      15
Name: count, dtype: int64

In [93]:
apps_df['Size'].value_counts()

Size
Varies with device    1526
11M                    188
12M                    186
13M                    186
14M                    182
                      ...
552k                     1
885k                     1
1020k                    1
582k                     1
619k                     1
Name: count, Length: 461, dtype: int64

In [94]:
apps_df['Price'].unique()

array([  0.  ,   4.99,   3.99,   6.99,   1.49,   2.99,   7.99,   5.99,
         3.49,   1.99,   9.99,   7.49,   0.99,   9.  ,   5.49,  10.  ,
        24.99,  11.99,  79.99,  16.99,  14.99,   1.  ,  29.99,  12.99,
         2.49,  10.99,   1.5 ,  19.99,  15.99,  33.99,  74.99,  39.99,
         3.95,   4.49,   1.7 ,   8.99,   2.  ,   3.88,  25.99, 399.99,
        17.99, 400.  ,   3.02,   1.76,   4.84,   4.77,   1.61,   2.5 ,
         1.59,   6.49,   1.29,   5.  ,  13.99, 299.99, 379.99,  37.99,
        18.99, 389.99,  19.9 ,   8.49,   1.75,  14.  ,   4.85,  46.99,
       109.99, 154.99,   3.08,   2.59,   4.8 ,   1.96,  19.4 ,   3.9 ,
         4.59,  15.46,   3.04,   4.29,   2.6 ,   3.28,   4.6 ,  28.99,
         2.95,   2.9 ,   1.97, 200.  ,  89.99,   2.56,  30.99,   3.61,
       394.99,   1.26,   1.2 ,   1.04])

In [96]:
#chek = len(app[app['Price]<0.0])
check = len(apps_df[apps_df['Price']<0.0])
check

0

In [100]:
apps_df.isnull().sum().sort_values(ascending=False)

Current Ver       8
Android Ver       2
Type              1
Category          0
App               0
Size              0
Reviews           0
Rating            0
Installs          0
Content Rating    0
Price             0
Last Updated      0
Genres            0
dtype: int64

In [101]:
apps_df['Current Ver'].isnull().sum()

np.int64(8)

In [102]:
apps_df[apps_df['Current Ver'].isnull()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
15,Learn To Draw Kawaii Characters,ART_AND_DESIGN,3.2,55.0,2.7M,5000.0,Free,0.00,Everyone,Art & Design,06-06-2018,NaN,4.2 and up
1553,Market Update Helper,LIBRARIES_AND_DEMO,4.1,20145.0,11k,1000000.0,Free,0.00,Everyone,Libraries & Demo,12-02-2013,NaN,1.5 and up
6322,Virtual DJ Sound Mixer,TOOLS,4.2,4010.0,8.7M,500000.0,Free,0.00,Everyone,Tools,10-05-2017,NaN,4.0 and up
6803,BT Master,FAMILY,0.0,0.0,222k,100.0,Free,0.00,Everyone,Education,06-11-2016,NaN,1.6 and up
7333,Dots puzzle,FAMILY,4.0,179.0,14M,50000.0,Paid,0.99,Everyone,Puzzle,18-04-2018,NaN,4.0 and up
7407,Calculate My IQ,FAMILY,0.0,44.0,7.2M,10000.0,Free,0.00,Everyone,Entertainment,03-04-2017,NaN,2.3 and up
7730,UFO-CQ,TOOLS,0.0,1.0,237k,10.0,Paid,0.99,Everyone,Tools,04-07-2016,NaN,2.0 and up
10342,La Fe de Jesus,BOOKS_AND_REFERENCE,0.0,8.0,658k,1000.0,Free,0.00,Everyone,Books & Reference,31-01-2017,NaN,3.0 and up

In [103]:
apps_df['Current Ver'] = apps_df['Current Ver'].replace(np.nan, 0)

In [105]:
apps_df['Current Ver'].isnull().sum()

np.int64(0)

In [106]:
apps_df['Current Ver'].unique()

array(['1.0.0', '2.0.0', '1.2.4', ..., '1.0.612928', '0.3.4', '2.0.148.0'],
      shape=(2784,), dtype=object)

In [108]:
len(apps_df[apps_df['Android Ver'] == 'Varies with device'])

1221

In [110]:
apps_df[apps_df['Android Ver'].isnull()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
4453,[substratum] Vacuum: P,PERSONALIZATION,4.4,230.0,11M,1000.0,Paid,1.49,Everyone,Personalization,20-07-2018,4.4,NaN
4490,Pi Dark [substratum],PERSONALIZATION,4.5,189.0,2.1M,10000.0,Free,0.00,Everyone,Personalization,27-03-2018,1.1,NaN

In [111]:
apps_df = apps_df[apps_df['Android Ver'] != 'Varies with device']

In [112]:
apps_df = apps_df[apps_df['Android Ver'].notnull()]

In [113]:
apps_df[apps_df['Android Ver'].isna()]

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver]
Index: []

In [114]:
apps_df.info()

<class 'pandas.DataFrame'>
Index: 9134 entries, 0 to 10838
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9134 non-null   str
 1   Category        9134 non-null   str
 2   Rating          9134 non-null   float64
 3   Reviews         9134 non-null   float64
 4   Size            9134 non-null   str
 5   Installs        9134 non-null   float64
 6   Type            9134 non-null   str
 7   Price           9134 non-null   float64
 8   Content Rating  9134 non-null   str
 9   Genres          9134 non-null   str
 10  Last Updated    9134 non-null   str
 11  Current Ver     9134 non-null   object
 12  Android Ver     9134 non-null   str
dtypes: float64(4), object(1), str(8)
memory usage: 999.0+ KB

In [115]:
apps_df['Last Updated']

0        07-01-2018
1        15-01-2018
2        01-08-2018
3        08-06-2018
4        20-06-2018
            ...
10834    18-06-2017
10835    29-09-2016
10836    25-07-2017
10837    06-07-2018
10838    20-01-2017
Name: Last Updated, Length: 9134, dtype: str

In [117]:
apps_df['Last Updated'] = pd.to_datetime(apps_df['Last Updated'], format='%d-%m-%y', errors='coerce')

apps_df['Last Updated'] = apps_df['Last Updated'].dt.strftime('%Y%m%d')

In [119]:
apps_df.to_csv('../data/cleaned/playstore_apps.csv')

In [122]:
len(apps_df)

9134

In [120]:
# reading plastore_reviews.csv
rev_df = pd.read_csv('../data/raw/playstore_reviews.csv')

In [123]:
rev_df.head(10)

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000
5,10 Best Foods for You,Best way,Positive,1.00,0.300000
6,10 Best Foods for You,Amazing,Positive,0.60,0.900000
7,10 Best Foods for You,NaN,NaN,NaN,NaN
8,10 Best Foods for You,"Looking forward app,",Neutral,0.00,0.000000
9,10 Best Foods for You,It helpful site ! It help foods get !,Neutral,0.00,0.000000

In [124]:
rev_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 64295 entries, 0 to 64294
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   App                     64295 non-null  str
 1   Translated_Review       37427 non-null  str
 2   Sentiment               37432 non-null  str
 3   Sentiment_Polarity      37432 non-null  float64
 4   Sentiment_Subjectivity  37432 non-null  float64
dtypes: float64(2), str(3)
memory usage: 2.5 MB

In [125]:
rev_df.columns

Index(['App', 'Translated_Review', 'Sentiment', 'Sentiment_Polarity',
       'Sentiment_Subjectivity'],
      dtype='str')

In [126]:
rev_df.shape

(64295, 5)

In [127]:
rev_df.isnull().sum()

App                           0
Translated_Review         26868
Sentiment                 26863
Sentiment_Polarity        26863
Sentiment_Subjectivity    26863
dtype: int64

In [128]:
rev_df['App'].unique()

<StringArray>
[                             '10 Best Foods for You',
                   '104 找工作 - 找工作 找打工 找兼職 履歷健檢 履歷診療室',
                                               '11st',
                         '1800 Contacts - Lens Store',
                    '1LINE – One Line with One Touch',
   '2018Emoji Keyboard 😂 Emoticons Lite -sticker&gif',
                       '21-Day Meditation Experience',
                '2Date Dating App, Love and matching',
                        '2GIS: directory & navigator',
                                          '2RedBeans',
 ...
                               'Hot Wheels: Race Off',
                'Hot or Not - Find someone right now',
   'HotelTonight: Book amazing deals at great hotels',
                      'Hotels Combined - Cheap deals',
 'Hotels.com: Book Hotel Rooms & Find Vacation Deals',
     'Hotspot Shield Free VPN Proxy & Wi-Fi Security',
                                            'Hotstar',
                     'Hotwire Hotel & Car Rental App',
                     'Housing-Real Estate & Property',
                        'Houzz Interior Design Ideas']
Length: 1074, dtype: str

In [129]:
rev_df[rev_df['App'] == 'nan']

Empty DataFrame
Columns: [App, Translated_Review, Sentiment, Sentiment_Polarity, Sentiment_Subjectivity]
Index: []

In [130]:
rev_df.duplicated().sum()

np.int64(33616)

In [131]:
rev_df.size

321475

In [132]:
rev_df = rev_df.drop_duplicates(keep='first')

In [133]:
rev_df.duplicated().sum()

np.int64(0)

In [135]:
rev_df.isnull().sum()

App                         0
Translated_Review         987
Sentiment                 982
Sentiment_Polarity        982
Sentiment_Subjectivity    982
dtype: int64

In [137]:
rev_df[rev_df['Translated_Review'].isnull()].head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
2,10 Best Foods for You,NaN,NaN,NaN,NaN
268,11st,NaN,Neutral,0.0,0.0
362,1LINE – One Line with One Touch,NaN,NaN,NaN,NaN
405,2018Emoji Keyboard 😂 Emoticons Lite -sticker&gif,NaN,NaN,NaN,NaN
539,"2Date Dating App, Love and matching",NaN,NaN,NaN,NaN

In [138]:
rev_df = rev_df[rev_df['Translated_Review'].notnull()]

In [139]:
rev_df['Sentiment'].unique()

<StringArray>
['Positive', 'Neutral', 'Negative']
Length: 3, dtype: str

In [140]:
rev_df['Sentiment_Polarity'].unique()

array([ 1.        ,  0.25      ,  0.4       , ..., -0.52857143,
       -0.37777778,  0.17333333], shape=(5410,))

In [141]:
rev_df['Sentiment_Subjectivity'].unique()

array([0.53333333, 0.28846154, 0.875     , ..., 0.51145833, 0.7172619 ,
       0.2594697 ], shape=(4474,))

In [142]:
rev_df[rev_df['Sentiment_Subjectivity'].isnull()].head()

Empty DataFrame
Columns: [App, Translated_Review, Sentiment, Sentiment_Polarity, Sentiment_Subjectivity]
Index: []

In [143]:
rev_df.info()

<class 'pandas.DataFrame'>
Index: 29692 entries, 0 to 64230
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   App                     29692 non-null  str
 1   Translated_Review       29692 non-null  str
 2   Sentiment               29692 non-null  str
 3   Sentiment_Polarity      29692 non-null  float64
 4   Sentiment_Subjectivity  29692 non-null  float64
dtypes: float64(2), str(3)
memory usage: 1.4 MB

In [144]:
rev_df.isnull().sum()

App                       0
Translated_Review         0
Sentiment                 0
Sentiment_Polarity        0
Sentiment_Subjectivity    0
dtype: int64

In [145]:
rev_df.head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000
5,10 Best Foods for You,Best way,Positive,1.00,0.300000

In [146]:
rev_df.to_csv('../data/cleaned/playstore_reviews.csv')

In [147]:
#both dataset were cleaned and stored.